name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: love-Liushuang/NotionNext
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for large files
        run: |
          git rev-list --objects --all | sort -k 2 -n | tail -n 10

      - name: Sync with remote repository
        run: |
          git remote add new-origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/love-Liushuang/NotionNextNews.git
          git fetch new-origin || echo "No remote repository yet, proceeding..."
          git reset --hard new-origin/main || echo "First push, skipping reset."
          git push -u new-origin main --force