name: Upstream Sync

on:
  schedule:
    - cron: "0 0 * * *" # 每天同步一次
  workflow_dispatch: # 手动触发

permissions:
  contents: write
  pull-requests: write # 允许创建 Pull Request

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出目标仓库
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: love-Liushuang/NotionNextNews
          ref: main

      # 2. 添加上游源仓库
      - name: Add upstream source repository
        run: |
          git remote add upstream https://github.com/love-Liushuang/NotionNext.git
          git fetch upstream

      # 3. 创建新分支并强制合并
      - name: Sync updates from upstream
        run: |
          git checkout -b sync-updates
          git merge upstream/main --allow-unrelated-histories --no-edit

      # 4. 推送新分支到目标仓库
      - name: Push updates to new branch
        run: |
          git push origin sync-updates

      # 5. 创建 Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Sync updates from upstream repository"
          branch: sync-updates
          base: main
          title: "Sync updates from upstream"
          body: |
            This Pull Request contains updates from the upstream repository.
            Please review and merge if all checks pass.